import React, { useState } from 'react';
import { Database, Check, Copy, RefreshCw, AlertTriangle, Layers, Download } from 'lucide-react';
import { SUPABASE_CONFIG } from '../supabaseClient';

interface DatabaseSetupModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSeedDatabase: () => Promise<void>;
  itemCount: number;
  isConnected: boolean;
  errorMessage?: string | null;
}

export const DatabaseSetupModal: React.FC<DatabaseSetupModalProps> = ({
  isOpen,
  onClose,
  onSeedDatabase,
  itemCount,
  isConnected,
  errorMessage
}) => {
  const [copied, setCopied] = useState(false);
  const [isSeeding, setIsSeeding] = useState(false);
  const [seedSuccess, setSeedSuccess] = useState(false);

  if (!isOpen) return null;

  const sqlSchema = `-- Run this in your Supabase SQL Editor:
CREATE TABLE IF NOT EXISTS public.twill_tape (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_name text,
  date text,
  booking_challan text,
  style text,
  order_no text,
  store_ref text,
  job_no text,
  colour text,
  item_name text,
  cm text,
  yds text,
  booking_qty numeric DEFAULT 0,
  receive_qty numeric DEFAULT 0,
  receive_date text,
  receive_challan text,
  issue_qty numeric DEFAULT 0,
  issue_date text,
  issue_challan text,
  balance_qty numeric DEFAULT 0,
  remarks text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.twill_tape ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on twill_tape" ON public.twill_tape FOR SELECT USING (true);
CREATE POLICY "Allow public insert on twill_tape" ON public.twill_tape FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on twill_tape" ON public.twill_tape FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on twill_tape" ON public.twill_tape FOR DELETE USING (true);

-- Sewing Thread Table
CREATE TABLE IF NOT EXISTS public.sewing_thread (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_name text,
  buyer text,
  date text,
  booking_challan text,
  style text,
  order_no text,
  store_ref text,
  s_thread_ref text,
  job_no text,
  colour text,
  color text,
  item_name text,
  thread_count text,
  count text,
  shade_no text,
  pantone text,
  sr_gt text,
  meter text,
  per_body_consm text,
  supplier text,
  qc_not_ok text,
  booking_qty numeric DEFAULT 0,
  receive_qty numeric DEFAULT 0,
  rcvd_date text,
  receive_date text,
  rcvd_challan text,
  receive_challan text,
  issue_qty numeric DEFAULT 0,
  issue_date text,
  issue_challan text,
  balance_qty numeric DEFAULT 0,
  remarks text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.sewing_thread ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on sewing_thread" ON public.sewing_thread FOR SELECT USING (true);
CREATE POLICY "Allow public insert on sewing_thread" ON public.sewing_thread FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on sewing_thread" ON public.sewing_thread FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on sewing_thread" ON public.sewing_thread FOR DELETE USING (true);
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSeed = async () => {
    try {
      setIsSeeding(true);
      await onSeedDatabase();
      setSeedSuccess(true);
      setTimeout(() => {
        setSeedSuccess(false);
        onClose();
      }, 1000);
    } catch (err) {
      console.error("Failed to seed database:", err);
    } finally {
      setIsSeeding(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="px-6 py-4 bg-slate-900 text-white flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-indigo-600 text-white">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold">Supabase Database Setup</h2>
              <p className="text-xs text-slate-300">Connected to: <code className="font-mono text-indigo-300">{SUPABASE_CONFIG.url}</code></p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            ✕
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6 max-h-[80vh] overflow-y-auto">
          
          {/* Status Banner */}
          <div className={`p-4 rounded-xl border flex items-start gap-3 ${
            isConnected 
              ? 'bg-emerald-50 border-emerald-200 text-emerald-950' 
              : 'bg-amber-50 border-amber-200 text-amber-950'
          }`}>
            <div className={`p-2 rounded-lg mt-0.5 ${isConnected ? 'bg-emerald-200 text-emerald-800' : 'bg-amber-200 text-amber-800'}`}>
              {isConnected ? <Check className="w-5 h-5" /> : <AlertTriangle className="w-5 h-5" />}
            </div>
            <div className="flex-1">
              <h4 className="text-sm font-bold">
                {isConnected ? `Supabase Connected (${itemCount} records in twill_tape)` : 'Supabase Connection or Table Notice'}
              </h4>
              <p className="text-xs mt-1 text-slate-600">
                {errorMessage || (isConnected ? 'Your database is connected and active.' : 'Make sure the table "twill_tape" exists in your Supabase project.')}
              </p>
            </div>
          </div>

          {/* Seed Action Button */}
          <div className="p-5 bg-gradient-to-br from-indigo-50 to-blue-50 border border-indigo-200 rounded-xl space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="text-sm font-bold text-indigo-950 flex items-center gap-2">
                  <Download className="w-4 h-4 text-indigo-600" />
                  Seed Sample Dataset into Supabase
                </h4>
                <p className="text-xs text-indigo-800 mt-0.5">
                  Populate your Supabase <code className="font-mono bg-indigo-100 px-1 rounded">twill_tape</code> table with initial records (Stanley Stella, KARIBAN, DIADORA).
                </p>
              </div>
            </div>

            <button
              onClick={handleSeed}
              disabled={isSeeding}
              className="w-full py-2.5 px-4 bg-indigo-600 hover:bg-indigo-700 active:scale-98 text-white font-bold text-sm rounded-xl shadow-sm transition-all flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {isSeeding ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  Uploading records to Supabase...
                </>
              ) : seedSuccess ? (
                <>
                  <Check className="w-4 h-4 text-emerald-300" />
                  Successfully Seeded!
                </>
              ) : (
                <>
                  <Layers className="w-4 h-4" />
                  Seed Initial Twill Tape Records to Supabase
                </>
              )}
            </button>
          </div>

          {/* SQL Schema Copy */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold uppercase tracking-wider text-slate-700">
                Table Schema SQL (Copy to Supabase SQL Editor if needed)
              </label>
              <button
                onClick={handleCopy}
                className="text-xs text-indigo-600 font-semibold hover:text-indigo-800 flex items-center gap-1"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied SQL!' : 'Copy SQL Script'}
              </button>
            </div>
            <pre className="p-4 bg-slate-900 text-slate-100 rounded-xl text-xs font-mono overflow-x-auto max-h-48 border border-slate-800">
              {sqlSchema}
            </pre>
          </div>

        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 text-sm font-bold text-slate-700 bg-white border border-slate-300 rounded-xl hover:bg-slate-100"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
